## Put comments here that give an overall description of what your
## functions do

## this takes a matrix and returns a list that have four function which set the matrix, get the matrix, set the inverse of matrix and get the inverse of matrix.

makeCacheMatrix <- function(x = matrix()) {
    
    inv<-NULL
    set<-function(y){
        x<<-y
        inv<<-NULL
    }
    
    get<-function()x
    setinv<-function(inverse)inv<<-inverse
    getinv <- function()inv
    list(set=set, get=get, setinv=setinv,getinv=getinv)

}


## This takes the list generated by makeCacheMatrix and compute the inverse and returned it if it is already not computed if computed already returned the cached value.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getinv()
        if(!is.null(inv)){
            message("getting cached inverse")
            return (inv)
        }
        matrix <- x$get()
        inv <- solve(matrix,...)
        x$setinv(inv)
        inv
        
}
